version: "3.9"

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8006:8006"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres-melon
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - melon2pgdata:/var/lib/postgresql/data
    
  redis:
    image: redis:7
    container_name: redis-melon
    ports:
      - "6379:6379"

  redis_gui:
    image: redis/redisinsight
    container_name: redis-interface
    ports:
      - "5540:5540"

volumes:
  melon2pgdata:
